import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import React, { useEffect, useState } from "react";
import { AuthProvider } from "./AuthContext";
import LogoutButton from "@/components/logoutButton";
import { ThemeProvider } from 'next-themes';
import { cn } from "@/lib/utils"
import OverlayButton from "@/components/logoutButton";



// Define or import the RootLayoutProps type
type RootLayoutProps = {
  children: React.ReactNode;
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: RootLayoutProps) {


  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}
      >
        
        
        <AuthProvider>
      
          <main>
      
      <div className="flex justify-center border-none  items-center border w-screen ">

      
              <OverlayButton />
              {children}
              </div>
      
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
