
import type { Metadata } from "next";

import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { ThemeProvider } from 'next-themes';





type RootLayoutProps = {
  children: React.ReactNode;
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {

  function cn(...classes: (string | undefined)[]): string {
    return classes.filter(Boolean).join(' ');
  } return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >


   <main >
 {children}
    </main>

      </body>
    </html>
  );
};

export default RootLayout;
